# version: '3.9'

services:
  dw:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_NAME=backend
      - DB_USER=backend
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    restart: always
    

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:

