# Generated by Django 5.0.8 on 2024-08-08 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь12', 'verbose_name_plural': 'Пользователи12'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('LAB', 'Labrador'), ('BEA', 'Beagle'), ('PUG', 'Pug'), ('POM', 'Pomeranian'), ('OTH', 'Other')], default='OTH', max_length=3, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Кличка животного'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин животного'),
        ),
        migrations.AlterField(
            model_name='walker',
            name='name',
            field=models.CharField(choices=[('Peter', 'Peter'), ('Anton', 'Anton')], default='Peter', max_length=5, verbose_name='Имя исполнителя'),
        ),
        migrations.AlterField(
            model_name='walkorder',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='walkorder',
            name='end_time',
            field=models.DateTimeField(verbose_name='Время окончания прогулки'),
        ),
        migrations.AlterField(
            model_name='walkorder',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_orders', to='dw.pet', verbose_name='Кличка животного'),
        ),
        migrations.AlterField(
            model_name='walkorder',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала прогулки'),
        ),
        migrations.AlterField(
            model_name='walkorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='walkorder',
            name='walker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_orders', to='dw.walker', verbose_name='Исполнитель'),
        ),
    ]
